// Países principales para selector rápido
export const MAIN_COUNTRIES = [
  { value: "estados-unidos", label: "Estados Unidos", isoCode: "us" },
  { value: "espana", label: "España", isoCode: "es" },
  { value: "guatemala", label: "Guatemala", isoCode: "gt" },
  { value: "mexico", label: "México", isoCode: "mx" },
];

// Opción especial para mostrar lista completa
export const OTHER_COUNTRY_OPTION = { value: "__otro__", label: "Otro país...", isoCode: undefined };

// Lista combinada para selector inicial (4 países + "Otro")
export const COUNTRY_QUICK_OPTIONS = [...MAIN_COUNTRIES, OTHER_COUNTRY_OPTION];

// Lista completa de países con códigos ISO
export const COUNTRIES = [
  { value: "afganistan", label: "Afganistán", isoCode: "af" },
  { value: "albania", label: "Albania", isoCode: "al" },
  { value: "alemania", label: "Alemania", isoCode: "de" },
  { value: "andorra", label: "Andorra", isoCode: "ad" },
  { value: "angola", label: "Angola", isoCode: "ao" },
  { value: "antigua-y-barbuda", label: "Antigua y Barbuda", isoCode: "ag" },
  { value: "arabia-saudita", label: "Arabia Saudita", isoCode: "sa" },
  { value: "argelia", label: "Argelia", isoCode: "dz" },
  { value: "argentina", label: "Argentina", isoCode: "ar" },
  { value: "armenia", label: "Armenia", isoCode: "am" },
  { value: "australia", label: "Australia", isoCode: "au" },
  { value: "austria", label: "Austria", isoCode: "at" },
  { value: "azerbaiyan", label: "Azerbaiyán", isoCode: "az" },
  { value: "bahamas", label: "Bahamas", isoCode: "bs" },
  { value: "bahrein", label: "Baréin", isoCode: "bh" },
  { value: "bangladesh", label: "Bangladesh", isoCode: "bd" },
  { value: "barbados", label: "Barbados", isoCode: "bb" },
  { value: "belarus", label: "Bielorrusia", isoCode: "by" },
  { value: "belgica", label: "Bélgica", isoCode: "be" },
  { value: "belice", label: "Belice", isoCode: "bz" },
  { value: "benin", label: "Benín", isoCode: "bj" },
  { value: "butan", label: "Bután", isoCode: "bt" },
  { value: "bolivia", label: "Bolivia", isoCode: "bo" },
  { value: "bosnia-herzegovina", label: "Bosnia y Herzegovina", isoCode: "ba" },
  { value: "botswana", label: "Botsuana", isoCode: "bw" },
  { value: "brasil", label: "Brasil", isoCode: "br" },
  { value: "brunei", label: "Brunéi", isoCode: "bn" },
  { value: "bulgaria", label: "Bulgaria", isoCode: "bg" },
  { value: "burkina-faso", label: "Burkina Faso", isoCode: "bf" },
  { value: "burundi", label: "Burundi", isoCode: "bi" },
  { value: "cabo-verde", label: "Cabo Verde", isoCode: "cv" },
  { value: "camboya", label: "Camboya", isoCode: "kh" },
  { value: "camerun", label: "Camerún", isoCode: "cm" },
  { value: "canada", label: "Canadá", isoCode: "ca" },
  { value: "catar", label: "Catar", isoCode: "qa" },
  { value: "chad", label: "Chad", isoCode: "td" },
  { value: "chile", label: "Chile", isoCode: "cl" },
  { value: "china", label: "China", isoCode: "cn" },
  { value: "chipre", label: "Chipre", isoCode: "cy" },
  { value: "colombia", label: "Colombia", isoCode: "co" },
  { value: "comoras", label: "Comoras", isoCode: "km" },
  { value: "congo", label: "Congo", isoCode: "cg" },
  { value: "congo-democratico", label: "Congo (República Democrática)", isoCode: "cd" },
  { value: "corea-del-norte", label: "Corea del Norte", isoCode: "kp" },
  { value: "corea-del-sur", label: "Corea del Sur", isoCode: "kr" },
  { value: "costa-de-marfil", label: "Costa de Marfil", isoCode: "ci" },
  { value: "costa-rica", label: "Costa Rica", isoCode: "cr" },
  { value: "croacia", label: "Croacia", isoCode: "hr" },
  { value: "cuba", label: "Cuba", isoCode: "cu" },
  { value: "dinamarca", label: "Dinamarca", isoCode: "dk" },
  { value: "djibouti", label: "Djibouti", isoCode: "dj" },
  { value: "dominica", label: "Dominica", isoCode: "dm" },
  { value: "ecuador", label: "Ecuador", isoCode: "ec" },
  { value: "egipto", label: "Egipto", isoCode: "eg" },
  { value: "el-salvador", label: "El Salvador", isoCode: "sv" },
  { value: "emiratos-arabes", label: "Emiratos Árabes Unidos", isoCode: "ae" },
  { value: "eritrea", label: "Eritrea", isoCode: "er" },
  { value: "eslovaquia", label: "Eslovaquia", isoCode: "sk" },
  { value: "eslovenia", label: "Eslovenia", isoCode: "si" },
  { value: "espana", label: "España", isoCode: "es" },
  { value: "estados-unidos", label: "Estados Unidos", isoCode: "us" },
  { value: "estonia", label: "Estonia", isoCode: "ee" },
  { value: "etiopia", label: "Etiopía", isoCode: "et" },
  { value: "fiji", label: "Fiyi", isoCode: "fj" },
  { value: "filipinas", label: "Filipinas", isoCode: "ph" },
  { value: "finlandia", label: "Finlandia", isoCode: "fi" },
  { value: "francia", label: "Francia", isoCode: "fr" },
  { value: "gabon", label: "Gabón", isoCode: "ga" },
  { value: "gambia", label: "Gambia", isoCode: "gm" },
  { value: "georgia", label: "Georgia", isoCode: "ge" },
  { value: "ghana", label: "Ghana", isoCode: "gh" },
  { value: "granada", label: "Granada", isoCode: "gd" },
  { value: "grecia", label: "Grecia", isoCode: "gr" },
  { value: "guatemala", label: "Guatemala", isoCode: "gt" },
  { value: "guinea", label: "Guinea", isoCode: "gn" },
  { value: "guinea-bissau", label: "Guinea-Bissau", isoCode: "gw" },
  { value: "guinea-ecuatorial", label: "Guinea Ecuatorial", isoCode: "gq" },
  { value: "guyana", label: "Guyana", isoCode: "gy" },
  { value: "haiti", label: "Haití", isoCode: "ht" },
  { value: "honduras", label: "Honduras", isoCode: "hn" },
  { value: "hungria", label: "Hungría", isoCode: "hu" },
  { value: "india", label: "India", isoCode: "in" },
  { value: "indonesia", label: "Indonesia", isoCode: "id" },
  { value: "irak", label: "Irak", isoCode: "iq" },
  { value: "iran", label: "Irán", isoCode: "ir" },
  { value: "irlanda", label: "Irlanda", isoCode: "ie" },
  { value: "islandia", label: "Islandia", isoCode: "is" },
  { value: "islas-marshall", label: "Islas Marshall", isoCode: "mh" },
  { value: "islas-salomon", label: "Islas Salomón", isoCode: "sb" },
  { value: "israel", label: "Israel", isoCode: "il" },
  { value: "italia", label: "Italia", isoCode: "it" },
  { value: "jamaica", label: "Jamaica", isoCode: "jm" },
  { value: "japon", label: "Japón", isoCode: "jp" },
  { value: "jordania", label: "Jordania", isoCode: "jo" },
  { value: "kazajistan", label: "Kazajistán", isoCode: "kz" },
  { value: "kenia", label: "Kenia", isoCode: "ke" },
  { value: "kirguistan", label: "Kirguistán", isoCode: "kg" },
  { value: "kiribati", label: "Kiribati", isoCode: "ki" },
  { value: "kuwait", label: "Kuwait", isoCode: "kw" },
  { value: "laos", label: "Laos", isoCode: "la" },
  { value: "lesotho", label: "Lesoto", isoCode: "ls" },
  { value: "letonia", label: "Letonia", isoCode: "lv" },
  { value: "libano", label: "Líbano", isoCode: "lb" },
  { value: "liberia", label: "Liberia", isoCode: "lr" },
  { value: "libia", label: "Libia", isoCode: "ly" },
  { value: "liechtenstein", label: "Liechtenstein", isoCode: "li" },
  { value: "lituania", label: "Lituania", isoCode: "lt" },
  { value: "luxemburgo", label: "Luxemburgo", isoCode: "lu" },
  { value: "macedonia", label: "Macedonia del Norte", isoCode: "mk" },
  { value: "madagascar", label: "Madagascar", isoCode: "mg" },
  { value: "malasia", label: "Malasia", isoCode: "my" },
  { value: "malawi", label: "Malaui", isoCode: "mw" },
  { value: "maldivas", label: "Maldivas", isoCode: "mv" },
  { value: "mali", label: "Malí", isoCode: "ml" },
  { value: "malta", label: "Malta", isoCode: "mt" },
  { value: "marruecos", label: "Marruecos", isoCode: "ma" },
  { value: "mauricio", label: "Mauricio", isoCode: "mu" },
  { value: "mauritania", label: "Mauritania", isoCode: "mr" },
  { value: "mexico", label: "México", isoCode: "mx" },
  { value: "micronesia", label: "Micronesia", isoCode: "fm" },
  { value: "moldavia", label: "Moldavia", isoCode: "md" },
  { value: "monaco", label: "Mónaco", isoCode: "mc" },
  { value: "mongolia", label: "Mongolia", isoCode: "mn" },
  { value: "montenegro", label: "Montenegro", isoCode: "me" },
  { value: "mozambique", label: "Mozambique", isoCode: "mz" },
  { value: "myanmar", label: "Myanmar", isoCode: "mm" },
  { value: "namibia", label: "Namibia", isoCode: "na" },
  { value: "nauru", label: "Nauru", isoCode: "nr" },
  { value: "nepal", label: "Nepal", isoCode: "np" },
  { value: "nicaragua", label: "Nicaragua", isoCode: "ni" },
  { value: "niger", label: "Níger", isoCode: "ne" },
  { value: "nigeria", label: "Nigeria", isoCode: "ng" },
  { value: "noruega", label: "Noruega", isoCode: "no" },
  { value: "nueva-zelanda", label: "Nueva Zelanda", isoCode: "nz" },
  { value: "oman", label: "Omán", isoCode: "om" },
  { value: "paises-bajos", label: "Países Bajos", isoCode: "nl" },
  { value: "pakistan", label: "Pakistán", isoCode: "pk" },
  { value: "palau", label: "Palaos", isoCode: "pw" },
  { value: "panama", label: "Panamá", isoCode: "pa" },
  { value: "papua-nueva-guinea", label: "Papúa Nueva Guinea", isoCode: "pg" },
  { value: "paraguay", label: "Paraguay", isoCode: "py" },
  { value: "peru", label: "Perú", isoCode: "pe" },
  { value: "polonia", label: "Polonia", isoCode: "pl" },
  { value: "portugal", label: "Portugal", isoCode: "pt" },
  { value: "reino-unido", label: "Reino Unido", isoCode: "gb" },
  { value: "republica-centroafricana", label: "República Centroafricana", isoCode: "cf" },
  { value: "republica-checa", label: "República Checa", isoCode: "cz" },
  { value: "republica-dominicana", label: "República Dominicana", isoCode: "do" },
  { value: "ruanda", label: "Ruanda", isoCode: "rw" },
  { value: "rumania", label: "Rumania", isoCode: "ro" },
  { value: "rusia", label: "Rusia", isoCode: "ru" },
  { value: "samoa", label: "Samoa", isoCode: "ws" },
  { value: "san-cristobal-nieves", label: "San Cristóbal y Nieves", isoCode: "kn" },
  { value: "san-marino", label: "San Marino", isoCode: "sm" },
  { value: "san-vicente-granadinas", label: "San Vicente y las Granadinas", isoCode: "vc" },
  { value: "santa-lucia", label: "Santa Lucía", isoCode: "lc" },
  { value: "santo-tome-principe", label: "Santo Tomé y Príncipe", isoCode: "st" },
  { value: "senegal", label: "Senegal", isoCode: "sn" },
  { value: "serbia", label: "Serbia", isoCode: "rs" },
  { value: "seychelles", label: "Seychelles", isoCode: "sc" },
  { value: "sierra-leona", label: "Sierra Leona", isoCode: "sl" },
  { value: "singapur", label: "Singapur", isoCode: "sg" },
  { value: "siria", label: "Siria", isoCode: "sy" },
  { value: "somalia", label: "Somalia", isoCode: "so" },
  { value: "sri-lanka", label: "Sri Lanka", isoCode: "lk" },
  { value: "sudafrica", label: "Sudáfrica", isoCode: "za" },
  { value: "sudan", label: "Sudán", isoCode: "sd" },
  { value: "sudan-del-sur", label: "Sudán del Sur", isoCode: "ss" },
  { value: "suecia", label: "Suecia", isoCode: "se" },
  { value: "suiza", label: "Suiza", isoCode: "ch" },
  { value: "surinam", label: "Surinam", isoCode: "sr" },
  { value: "tailandia", label: "Tailandia", isoCode: "th" },
  { value: "tanzania", label: "Tanzania", isoCode: "tz" },
  { value: "tayikistan", label: "Tayikistán", isoCode: "tj" },
  { value: "timor-oriental", label: "Timor Oriental", isoCode: "tl" },
  { value: "togo", label: "Togo", isoCode: "tg" },
  { value: "tonga", label: "Tonga", isoCode: "to" },
  { value: "trinidad-y-tobago", label: "Trinidad y Tobago", isoCode: "tt" },
  { value: "tunez", label: "Túnez", isoCode: "tn" },
  { value: "turkmenistan", label: "Turkmenistán", isoCode: "tm" },
  { value: "turquia", label: "Turquía", isoCode: "tr" },
  { value: "tuvalu", label: "Tuvalu", isoCode: "tv" },
  { value: "ucrania", label: "Ucrania", isoCode: "ua" },
  { value: "uganda", label: "Uganda", isoCode: "ug" },
  { value: "uruguay", label: "Uruguay", isoCode: "uy" },
  { value: "uzbekistan", label: "Uzbekistán", isoCode: "uz" },
  { value: "vanuatu", label: "Vanuatu", isoCode: "vu" },
  { value: "vaticano", label: "Ciudad del Vaticano", isoCode: "va" },
  { value: "venezuela", label: "Venezuela", isoCode: "ve" },
  { value: "vietnam", label: "Vietnam", isoCode: "vn" },
  { value: "yemen", label: "Yemen", isoCode: "ye" },
  { value: "zambia", label: "Zambia", isoCode: "zm" },
  { value: "zimbabue", label: "Zimbabue", isoCode: "zw" },
  { value: "otro", label: "Otro país", isoCode: undefined },
];

// Helper para obtener código ISO por value
export const getCountryIsoCode = (countryValue: string): string | undefined => {
  const allCountries = [...MAIN_COUNTRIES, ...COUNTRIES];
  return allCountries.find(c => c.value === countryValue)?.isoCode;
};

// Helper para obtener label por value
export const getCountryLabel = (countryValue: string): string | undefined => {
  const allCountries = [...MAIN_COUNTRIES, ...COUNTRIES];
  return allCountries.find(c => c.value === countryValue)?.label;
};
