export const COUNTRIES = [
  { value: "afganistan", label: "Afganistán" },
  { value: "albania", label: "Albania" },
  { value: "alemania", label: "Alemania" },
  { value: "andorra", label: "Andorra" },
  { value: "angola", label: "Angola" },
  { value: "antigua-y-barbuda", label: "Antigua y Barbuda" },
  { value: "arabia-saudita", label: "Arabia Saudita" },
  { value: "argelia", label: "Argelia" },
  { value: "argentina", label: "Argentina" },
  { value: "armenia", label: "Armenia" },
  { value: "australia", label: "Australia" },
  { value: "austria", label: "Austria" },
  { value: "azerbaiyan", label: "Azerbaiyán" },
  { value: "bahamas", label: "Bahamas" },
  { value: "bahrein", label: "Baréin" },
  { value: "bangladesh", label: "Bangladesh" },
  { value: "barbados", label: "Barbados" },
  { value: "belarus", label: "Bielorrusia" },
  { value: "belgica", label: "Bélgica" },
  { value: "belice", label: "Belice" },
  { value: "benin", label: "Benín" },
  { value: "butan", label: "Bután" },
  { value: "bolivia", label: "Bolivia" },
  { value: "bosnia-herzegovina", label: "Bosnia y Herzegovina" },
  { value: "botswana", label: "Botsuana" },
  { value: "brasil", label: "Brasil" },
  { value: "brunei", label: "Brunéi" },
  { value: "bulgaria", label: "Bulgaria" },
  { value: "burkina-faso", label: "Burkina Faso" },
  { value: "burundi", label: "Burundi" },
  { value: "cabo-verde", label: "Cabo Verde" },
  { value: "camboya", label: "Camboya" },
  { value: "camerun", label: "Camerún" },
  { value: "canada", label: "Canadá" },
  { value: "catar", label: "Catar" },
  { value: "chad", label: "Chad" },
  { value: "chile", label: "Chile" },
  { value: "china", label: "China" },
  { value: "chipre", label: "Chipre" },
  { value: "colombia", label: "Colombia" },
  { value: "comoras", label: "Comoras" },
  { value: "congo", label: "Congo" },
  { value: "congo-democratico", label: "Congo (República Democrática)" },
  { value: "corea-del-norte", label: "Corea del Norte" },
  { value: "corea-del-sur", label: "Corea del Sur" },
  { value: "costa-de-marfil", label: "Costa de Marfil" },
  { value: "costa-rica", label: "Costa Rica" },
  { value: "croacia", label: "Croacia" },
  { value: "cuba", label: "Cuba" },
  { value: "dinamarca", label: "Dinamarca" },
  { value: "djibouti", label: "Djibouti" },
  { value: "dominica", label: "Dominica" },
  { value: "ecuador", label: "Ecuador" },
  { value: "egipto", label: "Egipto" },
  { value: "el-salvador", label: "El Salvador" },
  { value: "emiratos-arabes", label: "Emiratos Árabes Unidos" },
  { value: "eritrea", label: "Eritrea" },
  { value: "eslovaquia", label: "Eslovaquia" },
  { value: "eslovenia", label: "Eslovenia" },
  { value: "espana", label: "España" },
  { value: "estados-unidos", label: "Estados Unidos" },
  { value: "estonia", label: "Estonia" },
  { value: "etiopia", label: "Etiopía" },
  { value: "fiji", label: "Fiyi" },
  { value: "filipinas", label: "Filipinas" },
  { value: "finlandia", label: "Finlandia" },
  { value: "francia", label: "Francia" },
  { value: "gabon", label: "Gabón" },
  { value: "gambia", label: "Gambia" },
  { value: "georgia", label: "Georgia" },
  { value: "ghana", label: "Ghana" },
  { value: "granada", label: "Granada" },
  { value: "grecia", label: "Grecia" },
  { value: "guatemala", label: "Guatemala" },
  { value: "guinea", label: "Guinea" },
  { value: "guinea-bissau", label: "Guinea-Bissau" },
  { value: "guinea-ecuatorial", label: "Guinea Ecuatorial" },
  { value: "guyana", label: "Guyana" },
  { value: "haiti", label: "Haití" },
  { value: "honduras", label: "Honduras" },
  { value: "hungria", label: "Hungría" },
  { value: "india", label: "India" },
  { value: "indonesia", label: "Indonesia" },
  { value: "irak", label: "Irak" },
  { value: "iran", label: "Irán" },
  { value: "irlanda", label: "Irlanda" },
  { value: "islandia", label: "Islandia" },
  { value: "islas-marshall", label: "Islas Marshall" },
  { value: "islas-salomon", label: "Islas Salomón" },
  { value: "israel", label: "Israel" },
  { value: "italia", label: "Italia" },
  { value: "jamaica", label: "Jamaica" },
  { value: "japon", label: "Japón" },
  { value: "jordania", label: "Jordania" },
  { value: "kazajistan", label: "Kazajistán" },
  { value: "kenia", label: "Kenia" },
  { value: "kirguistan", label: "Kirguistán" },
  { value: "kiribati", label: "Kiribati" },
  { value: "kuwait", label: "Kuwait" },
  { value: "laos", label: "Laos" },
  { value: "lesotho", label: "Lesoto" },
  { value: "letonia", label: "Letonia" },
  { value: "libano", label: "Líbano" },
  { value: "liberia", label: "Liberia" },
  { value: "libia", label: "Libia" },
  { value: "liechtenstein", label: "Liechtenstein" },
  { value: "lituania", label: "Lituania" },
  { value: "luxemburgo", label: "Luxemburgo" },
  { value: "macedonia", label: "Macedonia del Norte" },
  { value: "madagascar", label: "Madagascar" },
  { value: "malasia", label: "Malasia" },
  { value: "malawi", label: "Malaui" },
  { value: "maldivas", label: "Maldivas" },
  { value: "mali", label: "Malí" },
  { value: "malta", label: "Malta" },
  { value: "marruecos", label: "Marruecos" },
  { value: "mauricio", label: "Mauricio" },
  { value: "mauritania", label: "Mauritania" },
  { value: "mexico", label: "México" },
  { value: "micronesia", label: "Micronesia" },
  { value: "moldavia", label: "Moldavia" },
  { value: "monaco", label: "Mónaco" },
  { value: "mongolia", label: "Mongolia" },
  { value: "montenegro", label: "Montenegro" },
  { value: "mozambique", label: "Mozambique" },
  { value: "myanmar", label: "Myanmar" },
  { value: "namibia", label: "Namibia" },
  { value: "nauru", label: "Nauru" },
  { value: "nepal", label: "Nepal" },
  { value: "nicaragua", label: "Nicaragua" },
  { value: "niger", label: "Níger" },
  { value: "nigeria", label: "Nigeria" },
  { value: "noruega", label: "Noruega" },
  { value: "nueva-zelanda", label: "Nueva Zelanda" },
  { value: "oman", label: "Omán" },
  { value: "paises-bajos", label: "Países Bajos" },
  { value: "pakistan", label: "Pakistán" },
  { value: "palau", label: "Palaos" },
  { value: "panama", label: "Panamá" },
  { value: "papua-nueva-guinea", label: "Papúa Nueva Guinea" },
  { value: "paraguay", label: "Paraguay" },
  { value: "peru", label: "Perú" },
  { value: "polonia", label: "Polonia" },
  { value: "portugal", label: "Portugal" },
  { value: "reino-unido", label: "Reino Unido" },
  { value: "republica-centroafricana", label: "República Centroafricana" },
  { value: "republica-checa", label: "República Checa" },
  { value: "republica-dominicana", label: "República Dominicana" },
  { value: "ruanda", label: "Ruanda" },
  { value: "rumania", label: "Rumania" },
  { value: "rusia", label: "Rusia" },
  { value: "samoa", label: "Samoa" },
  { value: "san-cristobal-nieves", label: "San Cristóbal y Nieves" },
  { value: "san-marino", label: "San Marino" },
  { value: "san-vicente-granadinas", label: "San Vicente y las Granadinas" },
  { value: "santa-lucia", label: "Santa Lucía" },
  { value: "santo-tome-principe", label: "Santo Tomé y Príncipe" },
  { value: "senegal", label: "Senegal" },
  { value: "serbia", label: "Serbia" },
  { value: "seychelles", label: "Seychelles" },
  { value: "sierra-leona", label: "Sierra Leona" },
  { value: "singapur", label: "Singapur" },
  { value: "siria", label: "Siria" },
  { value: "somalia", label: "Somalia" },
  { value: "sri-lanka", label: "Sri Lanka" },
  { value: "sudafrica", label: "Sudáfrica" },
  { value: "sudan", label: "Sudán" },
  { value: "sudan-del-sur", label: "Sudán del Sur" },
  { value: "suecia", label: "Suecia" },
  { value: "suiza", label: "Suiza" },
  { value: "surinam", label: "Surinam" },
  { value: "tailandia", label: "Tailandia" },
  { value: "tanzania", label: "Tanzania" },
  { value: "tayikistan", label: "Tayikistán" },
  { value: "timor-oriental", label: "Timor Oriental" },
  { value: "togo", label: "Togo" },
  { value: "tonga", label: "Tonga" },
  { value: "trinidad-y-tobago", label: "Trinidad y Tobago" },
  { value: "tunez", label: "Túnez" },
  { value: "turkmenistan", label: "Turkmenistán" },
  { value: "turquia", label: "Turquía" },
  { value: "tuvalu", label: "Tuvalu" },
  { value: "ucrania", label: "Ucrania" },
  { value: "uganda", label: "Uganda" },
  { value: "uruguay", label: "Uruguay" },
  { value: "uzbekistan", label: "Uzbekistán" },
  { value: "vanuatu", label: "Vanuatu" },
  { value: "vaticano", label: "Ciudad del Vaticano" },
  { value: "venezuela", label: "Venezuela" },
  { value: "vietnam", label: "Vietnam" },
  { value: "yemen", label: "Yemen" },
  { value: "zambia", label: "Zambia" },
  { value: "zimbabue", label: "Zimbabue" },
  { value: "otro", label: "Otro país" },
]