project_id = "dfhoduirmqbarjnspbdh"

[functions.expire-quotes]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.test-notification]
verify_jwt = false

[functions.test-email]
verify_jwt = false

[functions.log-client-error]
verify_jwt = false

[functions.migrate-avatar-paths]
verify_jwt = false