// Centralized export of all hooks for better organization
export { useAuth, AuthProvider } from './useAuth';
export { useDashboardState } from './useDashboardState';
export { usePackagesData } from './usePackagesData';
export { useTripsData } from './useTripsData';
export { useOptimizedPackagesData } from './useOptimizedPackagesData';
export { useOptimizedTripsData } from './useOptimizedTripsData';
export { useAdminData } from './useAdminData';
export { useOptimizedRealtime } from './useOptimizedRealtime';
export { useNavigationState } from './useNavigationState';
export { useNotifications } from './useNotifications';
export { usePaymentOrders } from './usePaymentOrders';
export { useRealtimePackages } from './useRealtimePackages';
export { createOrUpdateTripPaymentAccumulator } from './useCreateTripPaymentAccumulator';
export { useDashboardActions } from './useDashboardActions';
export { useMatchFilters } from './useMatchFilters';

export { usePackageActions } from './usePackageActions';
export { usePackageChat } from './usePackageChat';
export { usePackageTimeline } from './usePackageTimeline';
export { usePendingActions } from './usePendingActions';
export { useStatusHelpers } from './useStatusHelpers';
export { useTripPayments } from './useTripPayments';
export { useUserManagement } from './useUserManagement';
export { useToast } from './use-toast';
export { useFavoronBankingInfo } from './useFavoronBankingInfo';
export { useUrlState } from './useUrlState';
export { usePersistedFormState } from './usePersistedFormState';
export { useModalProtection } from './useModalProtection';
export { useStickyState } from './useStickyState';
export { useSecureStorage } from './useSecureStorage';
export { usePhoneNumberValidation } from './usePhoneNumberValidation';